# Generated by Django 5.2.14 on 2026-05-18 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('planning_period', models.CharField(choices=[('year', 'Год'), ('quarter', 'Квартал'), ('month', 'Месяц'), ('week', 'Неделя')], default='week', max_length=16, verbose_name='Период планирования')),
                ('annual_goal', models.CharField(blank=True, max_length=240, verbose_name='Годовая цель')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('planned', 'Запланирована'), ('in_progress', 'В работе'), ('review', 'На согласовании'), ('done', 'Выполнена'), ('overdue', 'Просрочена'), ('cancelled', 'Отменена')], default='new', max_length=24, verbose_name='Статус')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='low', max_length=16, verbose_name='Риск')),
                ('risk_reason', models.TextField(blank=True, verbose_name='Причина риска')),
                ('risk_recommendation', models.TextField(blank=True, verbose_name='Рекомендация')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс, %')),
                ('tags', models.CharField(blank=True, max_length=240, verbose_name='Теги')),
                ('estimated_hours', models.PositiveSmallIntegerField(default=0, verbose_name='Плановые часы')),
                ('actual_hours', models.PositiveSmallIntegerField(default=0, verbose_name='Фактические часы')),
                ('needs_manager_attention', models.BooleanField(default=False, verbose_name='Требует внимания руководителя')),
                ('last_status_change_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее изменение статуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='departments.department', verbose_name='Отдел')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tasks.task', verbose_name='Родительская задача')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='departments.team', verbose_name='Команда')),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатели')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['deadline', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Комментарий к задаче',
                'verbose_name_plural': 'Комментарии к задачам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=80, verbose_name='Поле')),
                ('old_value', models.CharField(blank=True, max_length=240, verbose_name='Было')),
                ('new_value', models.CharField(blank=True, max_length=240, verbose_name='Стало')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История задачи',
                'verbose_name_plural': 'История задач',
                'ordering': ['-created_at'],
            },
        ),
    ]
