# Generated by Django 5.2.14 on 2026-05-19 18:37

from django.db import migrations, models


def convert_removed_statuses(apps, schema_editor):
    """Convert 'planned' and 'cancelled' tasks to 'new' before removing those choices."""
    Task = apps.get_model("tasks", "Task")
    Task.objects.filter(status__in=["planned", "cancelled"]).update(status="new")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_removed_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('review', 'На согласовании'), ('done', 'Выполнена'), ('overdue', 'Просрочена')], default='new', max_length=24, verbose_name='Статус'),
        ),
    ]
