# Generated by Django 5.2.14 on 2026-05-18 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('position', models.CharField(max_length=160, verbose_name='Должность')),
                ('role', models.CharField(choices=[('employee', 'Сотрудник'), ('team_lead', 'Руководитель команды'), ('department_head', 'Руководитель подразделения'), ('admin', 'Администратор')], default='employee', max_length=32, verbose_name='Роль')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар')),
                ('workload_index', models.CharField(choices=[('normal', 'Нормальная'), ('high', 'Высокая'), ('overloaded', 'Перегрузка')], default='normal', max_length=32, verbose_name='Индекс загрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department', verbose_name='Отдел')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.team', verbose_name='Команда')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['department__name', 'full_name'],
            },
        ),
    ]
